//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QHBASEPHIENHOP
{
    using System;
    using System.Collections.Generic;
    
    public partial class DMPhienHop
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DMPhienHop()
        {
            this.DMChuongTrinhLamViecs = new HashSet<DMChuongTrinhLamViec>();
            this.NoiDungs = new HashSet<NoiDung>();
            this.VanKienTaiLieus = new HashSet<VanKienTaiLieu>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> TenantId { get; set; }
        public System.DateTime CreationTime { get; set; }
        public Nullable<System.Guid> CreatorId { get; set; }
        public Nullable<System.DateTime> LastModificationTime { get; set; }
        public Nullable<System.Guid> LastModifierId { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.Guid> DeleterId { get; set; }
        public Nullable<System.DateTime> DeletionTime { get; set; }
        public string CreatorName { get; set; }
        public string DeletedName { get; set; }
        public string Description { get; set; }
        public string DescriptionSEO { get; set; }
        public Nullable<bool> IsShow { get; set; }
        public string KeyMainSEO { get; set; }
        public string KeyWordsSEO { get; set; }
        public string LastModifierName { get; set; }
        public Nullable<int> Order { get; set; }
        public string PageTitleSEO { get; set; }
        public Nullable<System.Guid> ParentId { get; set; }
        public string Title { get; set; }
        public string DetailCategoryRoot { get; set; }
        public string TreeParentIds { get; set; }
        public string UrlLink { get; set; }
        public Nullable<int> LoaiPhienHop { get; set; }
        public Nullable<int> OldId { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<int> ParentOldId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DMChuongTrinhLamViec> DMChuongTrinhLamViecs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NoiDung> NoiDungs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VanKienTaiLieu> VanKienTaiLieus { get; set; }
    }
}
