//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QHBASEPHIENHOP
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Preview_QuocHoi_PhienHopServiceEntities : DbContext
    {
        public Preview_QuocHoi_PhienHopServiceEntities()
            : base("name=Preview_QuocHoi_PhienHopServiceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChuongTrinhLamViec> ChuongTrinhLamViecs { get; set; }
        public virtual DbSet<DMChuongTrinhLamViec> DMChuongTrinhLamViecs { get; set; }
        public virtual DbSet<DMPhienHop> DMPhienHops { get; set; }
        public virtual DbSet<NoiDung> NoiDungs { get; set; }
        public virtual DbSet<ReplyNoiDung> ReplyNoiDungs { get; set; }
        public virtual DbSet<VanKienMapCQBH> VanKienMapCQBHs { get; set; }
        public virtual DbSet<VanKienTaiLieu> VanKienTaiLieus { get; set; }
    }
}
