//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QHBASEPHIENHOP
{
    using System;
    using System.Collections.Generic;
    
    public partial class VanKienTaiLieu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VanKienTaiLieu()
        {
            this.VanKienMapCQBHs = new HashSet<VanKienMapCQBH>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> TenantId { get; set; }
        public System.Guid DMPhienHopId { get; set; }
        public Nullable<System.Guid> LoaiVanKienId { get; set; }
        public Nullable<System.Guid> LinhVucId { get; set; }
        public int Status { get; set; }
        public string CreatorName { get; set; }
        public string LastModifierName { get; set; }
        public string DeletionName { get; set; }
        public string PageTitleSEO { get; set; }
        public string PageUrlSEO { get; set; }
        public string DescriptionSEO { get; set; }
        public string KeyMainSEO { get; set; }
        public string KeyWordsSEO { get; set; }
        public string Content { get; set; }
        public Nullable<System.DateTime> PublicDate { get; set; }
        public Nullable<int> ReadCount { get; set; }
        public Nullable<bool> ShareSocial { get; set; }
        public Nullable<bool> IsRead { get; set; }
        public string Image { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string ExtraProperties { get; set; }
        public string ConcurrencyStamp { get; set; }
        public System.DateTime CreationTime { get; set; }
        public Nullable<System.Guid> CreatorId { get; set; }
        public Nullable<System.DateTime> LastModificationTime { get; set; }
        public Nullable<System.Guid> LastModifierId { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.Guid> DeleterId { get; set; }
        public Nullable<System.DateTime> DeletionTime { get; set; }
        public Nullable<int> OldId { get; set; }
        public Nullable<int> AttachmentId { get; set; }
    
        public virtual DMPhienHop DMPhienHop { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VanKienMapCQBH> VanKienMapCQBHs { get; set; }
    }
}
