//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QHBASE
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class APATIT_FilesServicesEntities : DbContext
    {
        public APATIT_FilesServicesEntities()
            : base("name=APATIT_FilesServicesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__EFMigrationsHistory> C__EFMigrationsHistory { get; set; }
        public virtual DbSet<CMSFileAttachment> CMSFileAttachments { get; set; }
        public virtual DbSet<CMSFile> CMSFiles { get; set; }
        public virtual DbSet<CMSFileShared> CMSFileShareds { get; set; }
        public virtual DbSet<CMSInforUserByShared> CMSInforUserByShareds { get; set; }
    }
}
