//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QHBASE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Category()
        {
            this.NewCategories = new HashSet<NewCategory>();
        }
    
        public string Id { get; set; }
        public Nullable<System.Guid> TenantId { get; set; }
        public Nullable<int> Order { get; set; }
        public string Title { get; set; }
        public int Status { get; set; }
        public string ParentID { get; set; }
        public string Description { get; set; }
        public string PageUrl { get; set; }
        public string CreatorName { get; set; }
        public string LastModifierName { get; set; }
        public string DeletionName { get; set; }
        public string PageTitleSEO { get; set; }
        public string DescriptionSEO { get; set; }
        public string KeyMainSEO { get; set; }
        public string KeyWordsSEO { get; set; }
        public string TreeParentIds { get; set; }
        public string DetailCategoryRoot { get; set; }
        public string Language { get; set; }
        public string CategoryOldId { get; set; }
        public string ExtraProperties { get; set; }
        public string ConcurrencyStamp { get; set; }
        public System.DateTime CreationTime { get; set; }
        public Nullable<System.Guid> CreatorId { get; set; }
        public Nullable<System.DateTime> LastModificationTime { get; set; }
        public Nullable<System.Guid> LastModifierId { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.Guid> DeleterId { get; set; }
        public Nullable<System.DateTime> DeletionTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NewCategory> NewCategories { get; set; }
    }
}
