//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QHBASE
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class portalcdk_CommonsServiceEntities : DbContext
    {
        public portalcdk_CommonsServiceEntities()
            : base("name=portalcdk_CommonsServiceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__EFMigrationsHistory> C__EFMigrationsHistory { get; set; }
        public virtual DbSet<ConfigWebsite> ConfigWebsites { get; set; }
        public virtual DbSet<ContactInfo> ContactInfos { get; set; }
        public virtual DbSet<CoQuanBanHanh> CoQuanBanHanhs { get; set; }
        public virtual DbSet<DanhSachThongBao> DanhSachThongBaos { get; set; }
        public virtual DbSet<DataCloneService> DataCloneServices { get; set; }
        public virtual DbSet<Gopy> Gopys { get; set; }
        public virtual DbSet<HistoryActionFlow> HistoryActionFlows { get; set; }
        public virtual DbSet<HistoryVersion> HistoryVersions { get; set; }
        public virtual DbSet<Language> Languages { get; set; }
        public virtual DbSet<LanguageMapText> LanguageMapTexts { get; set; }
        public virtual DbSet<LanguageText> LanguageTexts { get; set; }
        public virtual DbSet<LienKetWebsite> LienKetWebsites { get; set; }
        public virtual DbSet<LinhVuc> LinhVucs { get; set; }
        public virtual DbSet<LoaiThongBao> LoaiThongBaos { get; set; }
        public virtual DbSet<LoaiVanKien> LoaiVanKiens { get; set; }
        public virtual DbSet<Menu> Menus { get; set; }
        public virtual DbSet<MenuLanhDao> MenuLanhDaos { get; set; }
        public virtual DbSet<Notification> Notifications { get; set; }
        public virtual DbSet<QuangCaoss> QuangCaosses { get; set; }
        public virtual DbSet<ReadCountLog> ReadCountLogs { get; set; }
        public virtual DbSet<SlideImage> SlideImages { get; set; }
        public virtual DbSet<TagInfo> TagInfos { get; set; }
        public virtual DbSet<Tag> Tags { get; set; }
        public virtual DbSet<ViTriQuangCao> ViTriQuangCaos { get; set; }
        public virtual DbSet<ViTriQuangCaoMapQuangCao> ViTriQuangCaoMapQuangCaos { get; set; }
        public virtual DbSet<WorkflowCategory> WorkflowCategories { get; set; }
        public virtual DbSet<WorkflowDefinition> WorkflowDefinitions { get; set; }
        public virtual DbSet<WorkflowInstance> WorkflowInstances { get; set; }
    }
}
