//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QHBASE
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class portalcdk_QuestionsAnswersEntities : DbContext
    {
        public portalcdk_QuestionsAnswersEntities()
            : base("name=portalcdk_QuestionsAnswersEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__EFMigrationsHistory> C__EFMigrationsHistory { get; set; }
        public virtual DbSet<Answer> Answers { get; set; }
        public virtual DbSet<FormResult> FormResults { get; set; }
        public virtual DbSet<FormSurvey> FormSurveys { get; set; }
        public virtual DbSet<FormSurveyAnswer> FormSurveyAnswers { get; set; }
        public virtual DbSet<FormSurveyQuestion> FormSurveyQuestions { get; set; }
        public virtual DbSet<Question> Questions { get; set; }
        public virtual DbSet<Topic> Topics { get; set; }
        public virtual DbSet<TopicSurvey> TopicSurveys { get; set; }
        public virtual DbSet<UserSurvey> UserSurveys { get; set; }
    }
}
