//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QHBASE
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CTTDTCDK_NewsServicesEntities : DbContext
    {
        public CTTDTCDK_NewsServicesEntities()
            : base("name=CTTDTCDK_NewsServicesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__EFMigrationsHistory> C__EFMigrationsHistory { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<CommentNew> CommentNews { get; set; }
        public virtual DbSet<Event> Events { get; set; }
        public virtual DbSet<HotNew> HotNews { get; set; }
        public virtual DbSet<HotNewLanhDao> HotNewLanhDaos { get; set; }
        public virtual DbSet<New> News { get; set; }
        public virtual DbSet<NewCategory> NewCategories { get; set; }
        public virtual DbSet<NewCoQuan> NewCoQuans { get; set; }
        public virtual DbSet<NewDBQH> NewDBQHs { get; set; }
        public virtual DbSet<NewKyHop> NewKyHops { get; set; }
        public virtual DbSet<NewPhienHop> NewPhienHops { get; set; }
        public virtual DbSet<NewRelate> NewRelates { get; set; }
        public virtual DbSet<NewTypeNew> NewTypeNews { get; set; }
        public virtual DbSet<NewVersion> NewVersions { get; set; }
        public virtual DbSet<NhuanBut> NhuanButs { get; set; }
        public virtual DbSet<NhuanButConfig> NhuanButConfigs { get; set; }
        public virtual DbSet<ReplyNew> ReplyNews { get; set; }
        public virtual DbSet<SettingSiteClone> SettingSiteClones { get; set; }
        public virtual DbSet<SummaryNewss> SummaryNewsses { get; set; }
        public virtual DbSet<TypeNew> TypeNews { get; set; }
    }
}
