//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QHBASE
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMSFileShared
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> TenantIdShareFrom { get; set; }
        public Nullable<System.Guid> TenantIdShareTo { get; set; }
        public Nullable<System.Guid> FileId { get; set; }
        public string CreatedByUserName { get; set; }
        public Nullable<System.Guid> TenantId { get; set; }
        public string FileContainerName { get; set; }
        public string Language { get; set; }
        public string ExtraProperties { get; set; }
        public string ConcurrencyStamp { get; set; }
        public System.DateTime CreationTime { get; set; }
        public Nullable<System.Guid> CreatorId { get; set; }
    
        public virtual CMSFile CMSFile { get; set; }
    }
}
