//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QHBASE
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMSFile
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CMSFile()
        {
            this.CMSFileAttachments = new HashSet<CMSFileAttachment>();
            this.CMSFileShareds = new HashSet<CMSFileShared>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> TenantId { get; set; }
        public Nullable<System.Guid> ParentId { get; set; }
        public string FileContainerName { get; set; }
        public string FileName { get; set; }
        public string MimeType { get; set; }
        public int FileType { get; set; }
        public int SubFilesQuantity { get; set; }
        public long ByteSize { get; set; }
        public string Hash { get; set; }
        public string BlobName { get; set; }
        public Nullable<System.Guid> OwnerUserId { get; set; }
        public string Flag { get; set; }
        public string FullPathServer { get; set; }
        public int FileExtention { get; set; }
        public Nullable<System.Guid> ParentIdThumb { get; set; }
        public string SizeThumb { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<bool> Shared { get; set; }
        public string FullPathServerThumb { get; set; }
        public Nullable<int> Order { get; set; }
        public string TreeParentIds { get; set; }
        public string DetailFolderRoot { get; set; }
        public Nullable<int> SubFoldersQuantity { get; set; }
        public string Language { get; set; }
        public string OldId { get; set; }
        public string ExtraProperties { get; set; }
        public string ConcurrencyStamp { get; set; }
        public System.DateTime CreationTime { get; set; }
        public Nullable<System.Guid> CreatorId { get; set; }
        public Nullable<System.DateTime> LastModificationTime { get; set; }
        public Nullable<System.Guid> LastModifierId { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.Guid> DeleterId { get; set; }
        public Nullable<System.DateTime> DeletionTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CMSFileAttachment> CMSFileAttachments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CMSFileShared> CMSFileShareds { get; set; }
    }
}
