//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QHBASE
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMSInforUserByShared
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> TenantId { get; set; }
        public System.DateTime CreationTime { get; set; }
        public System.Guid CreatorId { get; set; }
        public string CreatedByUserName { get; set; }
        public string CreatedByEmail { get; set; }
        public string Language { get; set; }
    }
}
