//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QHBASE
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactInfo
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> TenantId { get; set; }
        public string Title { get; set; }
        public string LogoHeader { get; set; }
        public string LogoFooter { get; set; }
        public string BannerHopTacDaoTao { get; set; }
        public string ManagementAgency { get; set; }
        public string LicenseNo { get; set; }
        public string NewsPageManager { get; set; }
        public string Address { get; set; }
        public string AddressMap { get; set; }
        public string PhoneNumber { get; set; }
        public string EmailMenuTop { get; set; }
        public string EmailMenuFooter { get; set; }
        public string Copyright { get; set; }
        public string UrlWebsite { get; set; }
        public string LinkFacebook { get; set; }
        public string LinkTwitter { get; set; }
        public string LinkSkype { get; set; }
        public string LinkGoogle { get; set; }
        public string LinkYoutube { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public string Language { get; set; }
        public string LinkInstagram { get; set; }
        public string LogoPartnership { get; set; }
        public string TitleWebsite { get; set; }
        public Nullable<int> TypeManager { get; set; }
        public string Messager { get; set; }
        public string Zalo { get; set; }
        public string PhoneNumber2 { get; set; }
        public string BannerTuyenSinh { get; set; }
        public string LinkPageBanner { get; set; }
        public string ExtraProperties { get; set; }
        public string ConcurrencyStamp { get; set; }
        public System.DateTime CreationTime { get; set; }
        public Nullable<System.Guid> CreatorId { get; set; }
        public Nullable<System.DateTime> LastModificationTime { get; set; }
        public Nullable<System.Guid> LastModifierId { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.Guid> DeleterId { get; set; }
        public Nullable<System.DateTime> DeletionTime { get; set; }
    }
}
