//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QHBASE
{
    using System;
    using System.Collections.Generic;
    
    public partial class DaiBieuQH
    {
        public int ID { get; set; }
        public string HoTen { get; set; }
        public string Ho { get; set; }
        public string Ten { get; set; }
        public string TenThuongGoi { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public bool GioiTinh { get; set; }
        public string DanToc { get; set; }
        public string TonGiao { get; set; }
        public string QueQuan { get; set; }
        public string TrinhDoHocVan { get; set; }
        public string TrinhDoChinhTri { get; set; }
        public string TrinhDoChuyenMon { get; set; }
        public string NgheNghiepChucVu { get; set; }
        public string NoiLamViec { get; set; }
        public string LaDangVienDang { get; set; }
        public Nullable<System.DateTime> NgayVaoDang { get; set; }
        public string KyLuat { get; set; }
        public string NoiDungCu { get; set; }
        public string DaiBieuQuocHoiKhoa { get; set; }
        public string DaiBieuChuyenTrach { get; set; }
        public string DaiBieuHoiDongNhanDan { get; set; }
        public string TrinhDoVanHoa { get; set; }
        public Nullable<System.DateTime> NgayVaoDangChinhThuc { get; set; }
        public string DTCoQuan { get; set; }
        public string DTNhaRieng { get; set; }
        public string DTDiDong { get; set; }
        public string Email { get; set; }
        public string Fax { get; set; }
        public string NoiUngCu { get; set; }
        public string NoiCuTru { get; set; }
        public string KhenThuong { get; set; }
        public string DBQHKhoa { get; set; }
        public string SourceUrl { get; set; }
        public byte[] AnhDaiDien { get; set; }
        public string PhuChu { get; set; }
        public string CoQuan { get; set; }
        public string TyLe { get; set; }
        public bool TrungCu { get; set; }
    }
}
