//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QHBASE
{
    using System;
    using System.Collections.Generic;
    
    public partial class DaiBieuQuocHoi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DaiBieuQuocHoi()
        {
            this.DaiBieuQuocHoiMapDmChucDanhs = new HashSet<DaiBieuQuocHoiMapDmChucDanh>();
            this.DaiBieuQuocHoiMapDmCoQuanQuocHois = new HashSet<DaiBieuQuocHoiMapDmCoQuanQuocHoi>();
            this.DaiBieuQuocHoiMapDmKhoaQuocHois = new HashSet<DaiBieuQuocHoiMapDmKhoaQuocHoi>();
            this.DonViMapChucVus = new HashSet<DonViMapChucVu>();
            this.TimeLineDBQHs = new HashSet<TimeLineDBQH>();
        }
    
        public string Id { get; set; }
        public Nullable<System.Guid> TenantId { get; set; }
        public string FullName { get; set; }
        public string SurName { get; set; }
        public string Name { get; set; }
        public string TenThuongGoi { get; set; }
        public Nullable<System.Guid> GioiTinhId { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string QueQuan { get; set; }
        public string NoiCuTru { get; set; }
        public Nullable<System.Guid> DanTocId { get; set; }
        public Nullable<System.Guid> TonGiaoId { get; set; }
        public string TrinhDoVanHoa { get; set; }
        public Nullable<System.Guid> TrinhDoHocVanId { get; set; }
        public string TrinhDoChuyenMon { get; set; }
        public Nullable<System.Guid> TrinhDoChinhTriId { get; set; }
        public Nullable<bool> IsDangVien { get; set; }
        public Nullable<System.DateTime> NgayVaoDang { get; set; }
        public Nullable<System.DateTime> NgayVaoDangChinhThuc { get; set; }
        public Nullable<System.Guid> NoiUngCuId { get; set; }
        public string NoiLamViec { get; set; }
        public string NgheNghiepChucVu { get; set; }
        public Nullable<System.Guid> DaiBieuChuyenTrachId { get; set; }
        public string DaiBieuHoiDongNhanDan { get; set; }
        public string DienThoaiNhaRieng { get; set; }
        public string DienThoaiCoQuan { get; set; }
        public string DienThoaiDiDong { get; set; }
        public string Email { get; set; }
        public string Fax { get; set; }
        public string KhenThuong { get; set; }
        public string KyLuat { get; set; }
        public string PhuChu { get; set; }
        public string Image { get; set; }
        public int Order { get; set; }
        public bool IsShow { get; set; }
        public string UpdatedBy { get; set; }
        public string CreatedBy { get; set; }
        public string BannerBackgroud { get; set; }
        public string Language { get; set; }
        public Nullable<bool> HienThiThongTinChiTiet { get; set; }
        public string ExtraProperties { get; set; }
        public string ConcurrencyStamp { get; set; }
        public System.DateTime CreationTime { get; set; }
        public Nullable<System.Guid> CreatorId { get; set; }
        public Nullable<System.DateTime> LastModificationTime { get; set; }
        public Nullable<System.Guid> LastModifierId { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.Guid> DeleterId { get; set; }
        public Nullable<System.DateTime> DeletionTime { get; set; }
    
        public virtual DmDanToc DmDanToc { get; set; }
        public virtual DmTonGiao DmTonGiao { get; set; }
        public virtual GioiTinh GioiTinh { get; set; }
        public virtual TrinhDoChinhTri TrinhDoChinhTri { get; set; }
        public virtual TrinhDoHocVan TrinhDoHocVan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DaiBieuQuocHoiMapDmChucDanh> DaiBieuQuocHoiMapDmChucDanhs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DaiBieuQuocHoiMapDmCoQuanQuocHoi> DaiBieuQuocHoiMapDmCoQuanQuocHois { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DaiBieuQuocHoiMapDmKhoaQuocHoi> DaiBieuQuocHoiMapDmKhoaQuocHois { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonViMapChucVu> DonViMapChucVus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TimeLineDBQH> TimeLineDBQHs { get; set; }
    }
}
