//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QHBASE
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhSachThongBao
    {
        public string Id { get; set; }
        public string TieuDe { get; set; }
        public string SoThongBao { get; set; }
        public string IdLoaiThongBao { get; set; }
        public string MoTa { get; set; }
        public string NoiDung { get; set; }
        public Nullable<System.DateTime> NgayThongBao { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<int> Status { get; set; }
        public string Language { get; set; }
        public string TieuDeUnicode { get; set; }
        public string MoTaUnicode { get; set; }
        public string Image { get; set; }
        public Nullable<int> ViewCount { get; set; }
        public string DetailLinkClone { get; set; }
        public string ExtraProperties { get; set; }
        public string ConcurrencyStamp { get; set; }
        public System.DateTime CreationTime { get; set; }
        public Nullable<System.Guid> CreatorId { get; set; }
        public Nullable<System.DateTime> LastModificationTime { get; set; }
        public Nullable<System.Guid> LastModifierId { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.Guid> DeleterId { get; set; }
        public Nullable<System.DateTime> DeletionTime { get; set; }
    
        public virtual LoaiThongBao LoaiThongBao { get; set; }
    }
}
