//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QHBASE
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhMucChung
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DanhMucChung()
        {
            this.DanhSachCacCoSoGiaoDucs = new HashSet<DanhSachCacCoSoGiaoDuc>();
            this.DanhSachCacCoSoGiaoDucs1 = new HashSet<DanhSachCacCoSoGiaoDuc>();
            this.DanhSachCacCoSoGiaoDucs2 = new HashSet<DanhSachCacCoSoGiaoDuc>();
        }
    
        public string Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<int> Order { get; set; }
        public bool IsShow { get; set; }
        public string CreatorName { get; set; }
        public string LastModifierName { get; set; }
        public string ParentId { get; set; }
        public Nullable<int> OldID { get; set; }
        public Nullable<int> ParentOldID { get; set; }
        public string TreeParentIds { get; set; }
        public string DetailCategoryRoot { get; set; }
        public string Language { get; set; }
        public Nullable<int> DanhMucDungChungType { get; set; }
        public System.DateTime CreationTime { get; set; }
        public Nullable<System.Guid> CreatorId { get; set; }
        public Nullable<System.DateTime> LastModificationTime { get; set; }
        public Nullable<System.Guid> LastModifierId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DanhSachCacCoSoGiaoDuc> DanhSachCacCoSoGiaoDucs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DanhSachCacCoSoGiaoDuc> DanhSachCacCoSoGiaoDucs1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DanhSachCacCoSoGiaoDuc> DanhSachCacCoSoGiaoDucs2 { get; set; }
    }
}
