//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QHBASE
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhSachCongKhaiNganSach
    {
        public string Id { get; set; }
        public string Title { get; set; }
        public string NamKyBaoCao { get; set; }
        public string BieuMau { get; set; }
        public string LawId { get; set; }
        public string DMCongKhaiNganSachId { get; set; }
        public string TitleUnicode { get; set; }
        public string SoQuyetDinhCongBo { get; set; }
        public Nullable<System.DateTime> NgayCongBo { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public string DeletedBy { get; set; }
        public bool IsShow { get; set; }
        public string Language { get; set; }
        public string ExtraProperties { get; set; }
        public string ConcurrencyStamp { get; set; }
        public System.DateTime CreationTime { get; set; }
        public Nullable<System.Guid> CreatorId { get; set; }
        public Nullable<System.DateTime> LastModificationTime { get; set; }
        public Nullable<System.Guid> LastModifierId { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.Guid> DeleterId { get; set; }
        public Nullable<System.DateTime> DeletionTime { get; set; }
    
        public virtual Law Law { get; set; }
    }
}
