//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QHBASE
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhSachCacCoSoGiaoDuc
    {
        public string Id { get; set; }
        public string Title { get; set; }
        public string LoaiHinhCoSoDaoTaoId { get; set; }
        public string LoaiTruongId { get; set; }
        public string TinhThanhPhoId { get; set; }
        public string KyHieu { get; set; }
        public string TenTiengAnh { get; set; }
        public string Website { get; set; }
        public Nullable<System.DateTime> NgayCapGiayChungNhan { get; set; }
        public Nullable<System.DateTime> NgayHetHanGiayChungNhan { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public string DeletedBy { get; set; }
        public bool IsShow { get; set; }
        public string Language { get; set; }
        public Nullable<int> Order { get; set; }
        public System.DateTime CreationTime { get; set; }
        public Nullable<System.Guid> CreatorId { get; set; }
        public Nullable<System.DateTime> LastModificationTime { get; set; }
        public Nullable<System.Guid> LastModifierId { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.Guid> DeleterId { get; set; }
        public Nullable<System.DateTime> DeletionTime { get; set; }
    
        public virtual DanhMucChung DanhMucChung { get; set; }
        public virtual DanhMucChung DanhMucChung1 { get; set; }
        public virtual DanhMucChung DanhMucChung2 { get; set; }
    }
}
