//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QHBASE
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhSachSanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DanhSachSanPham()
        {
            this.PhanHoiSanPhams = new HashSet<PhanHoiSanPham>();
        }
    
        public string Id { get; set; }
        public string TenSanPham { get; set; }
        public string MaSanPham { get; set; }
        public string MoTa { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public string NoiDung { get; set; }
        public string HinhAnh { get; set; }
        public string NguoiTao { get; set; }
        public string NguoiSua { get; set; }
        public string NguoiXoa { get; set; }
        public string Language { get; set; }
        public Nullable<int> Status { get; set; }
        public int LuotView { get; set; }
        public bool IsHomePage { get; set; }
        public bool IsShared { get; set; }
        public string ExtraProperties { get; set; }
        public string ConcurrencyStamp { get; set; }
        public System.DateTime CreationTime { get; set; }
        public Nullable<System.Guid> CreatorId { get; set; }
        public Nullable<System.DateTime> LastModificationTime { get; set; }
        public Nullable<System.Guid> LastModifierId { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.Guid> DeleterId { get; set; }
        public Nullable<System.DateTime> DeletionTime { get; set; }
        public string HinhAnhList { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhanHoiSanPham> PhanHoiSanPhams { get; set; }
    }
}
