//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QHBASE
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataCloneService
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> TenantId { get; set; }
        public string CreatorName { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> PublicDate { get; set; }
        public string StatusName { get; set; }
        public int TypeCloneService { get; set; }
        public string CoQuanSoanThao { get; set; }
        public string CoQuanThamTra { get; set; }
        public string CoQuanTrinhDuThao { get; set; }
        public Nullable<bool> DaThongQua { get; set; }
        public string LinhVuc { get; set; }
        public Nullable<int> LuotXem { get; set; }
        public string NgayCapNhat { get; set; }
        public string PhamViDieuChinh { get; set; }
        public string ThaoLuanTaiKhoa { get; set; }
        public string ThaoLuanTaiKyHop { get; set; }
        public string ThongQuaTaiKhoa { get; set; }
        public string ThongQuaTaiKyHop { get; set; }
        public string OldId { get; set; }
        public string Image { get; set; }
        public string LinkFileVideo { get; set; }
        public string LinkDetail { get; set; }
        public System.DateTime CreationTime { get; set; }
        public Nullable<System.Guid> CreatorId { get; set; }
    }
}
