//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QHBASE
{
    using System;
    using System.Collections.Generic;
    
    public partial class DmLichLamViec
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DmLichLamViec()
        {
            this.LichLamViecs = new HashSet<LichLamViec>();
        }
    
        public string Id { get; set; }
        public Nullable<System.Guid> TenantId { get; set; }
        public Nullable<System.DateTime> Workday { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public string Author { get; set; }
        public int Status { get; set; }
        public int TypeLich { get; set; }
        public Nullable<System.DateTime> PublicDate { get; set; }
        public Nullable<bool> ShareSocial { get; set; }
        public string CreatorName { get; set; }
        public string LastModifierName { get; set; }
        public string DeletionName { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<int> OldId { get; set; }
        public string Language { get; set; }
        public string ExtraProperties { get; set; }
        public string ConcurrencyStamp { get; set; }
        public System.DateTime CreationTime { get; set; }
        public Nullable<System.Guid> CreatorId { get; set; }
        public Nullable<System.DateTime> LastModificationTime { get; set; }
        public Nullable<System.Guid> LastModifierId { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.Guid> DeleterId { get; set; }
        public Nullable<System.DateTime> DeletionTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LichLamViec> LichLamViecs { get; set; }
    }
}
