//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QHBASE
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonViMapChucVu
    {
        public string DaiBieuQuocHoiId { get; set; }
        public System.Guid DonViId { get; set; }
        public System.Guid ChucVuId { get; set; }
        public Nullable<System.Guid> DmChucDanhId { get; set; }
        public Nullable<System.Guid> DmCoQuanQuocHoiId { get; set; }
        public System.Guid Id { get; set; }
    
        public virtual DaiBieuQuocHoi DaiBieuQuocHoi { get; set; }
        public virtual DmChucDanh DmChucDanh { get; set; }
        public virtual DmChucDanh DmChucDanh1 { get; set; }
        public virtual DmCoQuanQuocHoi DmCoQuanQuocHoi { get; set; }
        public virtual DmCoQuanQuocHoi DmCoQuanQuocHoi1 { get; set; }
    }
}
