//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QHBASE
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailDangKy
    {
        public System.Guid Id { get; set; }
        public string HoTen { get; set; }
        public string Email { get; set; }
        public bool GuiAllThongTin { get; set; }
        public bool GuiThongTinSanPham { get; set; }
        public bool GuiThongTinTinTuc { get; set; }
        public System.DateTime CreationTime { get; set; }
        public Nullable<System.Guid> CreatorId { get; set; }
    }
}
