//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QHBASE
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormSurvey
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FormSurvey()
        {
            this.FormSurveyQuestions = new HashSet<FormSurveyQuestion>();
            this.UserSurveys = new HashSet<UserSurvey>();
        }
    
        public string Id { get; set; }
        public Nullable<System.Guid> TenantId { get; set; }
        public string FormTitle { get; set; }
        public string FormDescription { get; set; }
        public int Order { get; set; }
        public bool IsShow { get; set; }
        public Nullable<System.Guid> TopicId { get; set; }
        public string BannerForm { get; set; }
        public bool UserInfoRequest { get; set; }
        public string UpdatedBy { get; set; }
        public string CreatedBy { get; set; }
        public string Language { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public string ExtraProperties { get; set; }
        public string ConcurrencyStamp { get; set; }
        public System.DateTime CreationTime { get; set; }
        public Nullable<System.Guid> CreatorId { get; set; }
        public Nullable<System.DateTime> LastModificationTime { get; set; }
        public Nullable<System.Guid> LastModifierId { get; set; }
    
        public virtual Topic Topic { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormSurveyQuestion> FormSurveyQuestions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserSurvey> UserSurveys { get; set; }
    }
}
