//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QHBASE
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormResult
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> TenantId { get; set; }
        public System.Guid FormSurveyQuestionId { get; set; }
        public string AnswerResponseContent { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public Nullable<System.Guid> UserSurveyId { get; set; }
        public string IpAddress { get; set; }
    
        public virtual FormSurveyQuestion FormSurveyQuestion { get; set; }
        public virtual UserSurvey UserSurvey { get; set; }
    }
}
