//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QHBASE
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormSurveyAnswer
    {
        public System.Guid Id { get; set; }
        public int Order { get; set; }
        public bool IsShow { get; set; }
        public string UpdatedBy { get; set; }
        public string CreatedBy { get; set; }
        public string NoiDung { get; set; }
        public System.Guid FormSurveyQuestionId { get; set; }
        public string ExtraProperties { get; set; }
        public string ConcurrencyStamp { get; set; }
        public System.DateTime CreationTime { get; set; }
        public Nullable<System.Guid> CreatorId { get; set; }
        public Nullable<System.DateTime> LastModificationTime { get; set; }
        public Nullable<System.Guid> LastModifierId { get; set; }
    
        public virtual FormSurveyQuestion FormSurveyQuestion { get; set; }
    }
}
