//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QHBASE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gallery
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> TenantId { get; set; }
        public string Title { get; set; }
        public int Order { get; set; }
        public string Description { get; set; }
        public int Status { get; set; }
        public string Image { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public string DeletedBy { get; set; }
        public System.Guid CategoryGalleryId { get; set; }
        public string CategoryGalleryTree { get; set; }
        public string CategoryGalleryTitle { get; set; }
        public string OrganizationUnitCode { get; set; }
        public Nullable<System.Guid> OrganizationUnitId { get; set; }
        public string OrganizationUnitName { get; set; }
        public long GalleryIndex { get; set; }
        public string Language { get; set; }
        public string ExtraProperties { get; set; }
        public string ConcurrencyStamp { get; set; }
        public System.DateTime CreationTime { get; set; }
        public Nullable<System.Guid> CreatorId { get; set; }
        public Nullable<System.DateTime> LastModificationTime { get; set; }
        public Nullable<System.Guid> LastModifierId { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.Guid> DeleterId { get; set; }
        public Nullable<System.DateTime> DeletionTime { get; set; }
    
        public virtual CategoryGallery CategoryGallery { get; set; }
    }
}
