//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QHBASE
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoryActionFlow
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> WORKFLOW_INSTANCE_ID { get; set; }
        public string NODE_ID { get; set; }
        public string NODE_NAME { get; set; }
        public string ACTION_NODE { get; set; }
        public Nullable<System.Guid> FROM_USER_ID { get; set; }
        public string LIST_TO_USER_ID { get; set; }
        public string LIST_TO_NODE_ID { get; set; }
        public string LIST_TO_ROLE_ID { get; set; }
        public string ExtraProperties { get; set; }
        public string ConcurrencyStamp { get; set; }
        public System.DateTime CreationTime { get; set; }
        public Nullable<System.Guid> CreatorId { get; set; }
        public Nullable<System.DateTime> LastModificationTime { get; set; }
        public Nullable<System.Guid> LastModifierId { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.Guid> DeleterId { get; set; }
        public Nullable<System.DateTime> DeletionTime { get; set; }
    
        public virtual WorkflowInstance WorkflowInstance { get; set; }
    }
}
