//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QHBASE
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotNewLanhDao
    {
        public string HotNewId { get; set; }
        public string LanhDaoId { get; set; }
    
        public virtual HotNew HotNew { get; set; }
    }
}
