//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QHBASE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Law
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Law()
        {
            this.LawCategories = new HashSet<LawCategory>();
            this.LawFields = new HashSet<LawField>();
            this.LawSigners = new HashSet<LawSigner>();
            this.DanhSachCongKhaiNganSaches = new HashSet<DanhSachCongKhaiNganSach>();
        }
    
        public string Id { get; set; }
        public Nullable<System.Guid> TenantId { get; set; }
        public string Title { get; set; }
        public Nullable<int> Status { get; set; }
        public string OfficialNumber { get; set; }
        public Nullable<System.DateTime> PublishedDate { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public Nullable<System.DateTime> PublicDate { get; set; }
        public string Source { get; set; }
        public string EffectiveArea { get; set; }
        public Nullable<bool> Shared { get; set; }
        public string Tags { get; set; }
        public string Content { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public string DeletedBy { get; set; }
        public string IdEffectStatus { get; set; }
        public string EffectStatusTitle { get; set; }
        public string IdTypeOfDocument { get; set; }
        public string TypeOfDocumentTitle { get; set; }
        public string Language { get; set; }
        public string PageTitleSEO { get; set; }
        public string PageUrlSEO { get; set; }
        public string DescriptionSEO { get; set; }
        public string KeyMainSEO { get; set; }
        public string KeyWordsSEO { get; set; }
        public string OrganizationUnitCode { get; set; }
        public Nullable<System.Guid> OrganizationUnitId { get; set; }
        public string OrganizationUnitName { get; set; }
        public Nullable<bool> IsMinistry { get; set; }
        public Nullable<System.Guid> QuyTrinhId { get; set; }
        public string QuyTrinhName { get; set; }
        public Nullable<int> VanBanQCTC { get; set; }
        public string DetailLinkClone { get; set; }
        public string ExtraProperties { get; set; }
        public string ConcurrencyStamp { get; set; }
        public System.DateTime CreationTime { get; set; }
        public Nullable<System.Guid> CreatorId { get; set; }
        public Nullable<System.DateTime> LastModificationTime { get; set; }
        public Nullable<System.Guid> LastModifierId { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.Guid> DeleterId { get; set; }
        public Nullable<System.DateTime> DeletionTime { get; set; }
    
        public virtual EffectStatu EffectStatu { get; set; }
        public virtual TypeOfDocument TypeOfDocument { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LawCategory> LawCategories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LawField> LawFields { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LawSigner> LawSigners { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DanhSachCongKhaiNganSach> DanhSachCongKhaiNganSaches { get; set; }
    }
}
