//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QHBASE
{
    using System;
    using System.Collections.Generic;
    
    public partial class LawCategory
    {
        public System.Guid Id { get; set; }
        public string LawId { get; set; }
        public string CategoryId { get; set; }
    
        public virtual Law Law { get; set; }
    }
}
