//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QHBASE
{
    using System;
    using System.Collections.Generic;
    
    public partial class LawSigner
    {
        public string IdLaw { get; set; }
        public string IdSigner { get; set; }
        public string IdPromulgator { get; set; }
        public string Position { get; set; }
        public System.Guid Id { get; set; }
    
        public virtual Law Law { get; set; }
        public virtual Promulgator Promulgator { get; set; }
        public virtual Signer Signer { get; set; }
    }
}
