//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QHBASE
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuLanhDao
    {
        public System.Guid Id { get; set; }
        public string Title { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public string PageUrl { get; set; }
        public string Position { get; set; }
        public bool IsMenuTinHoatDong { get; set; }
        public string TitleMenuTinHoatDong { get; set; }
        public string CategoryIdMenuTinHoatDong { get; set; }
        public int OrderMenuTinHoatDong { get; set; }
        public bool IsMenuTieuSu { get; set; }
        public string TitleMenuTieuSu { get; set; }
        public string CategoryIdMenuTieuSu { get; set; }
        public int OrderMenuTieuSu { get; set; }
        public bool IsMenuTinChiDao { get; set; }
        public string TitleMenuTinChiDao { get; set; }
        public string CategoryIdMenuTinChiDao { get; set; }
        public int OrderMenuTinChiDao { get; set; }
        public bool IsMenuTinBaiPhatBieu { get; set; }
        public string TitleMenuTinBaiPhatBieu { get; set; }
        public string CategoryIdMenuTinBaiPhatBieu { get; set; }
        public int OrderMenuTinBaiPhatBieu { get; set; }
        public bool IsShowMenuTrangChu { get; set; }
        public string TitleMenuLienHe { get; set; }
        public bool IsShowMenuLienHe { get; set; }
        public string LinkMenuLienHe { get; set; }
        public bool IsDefault { get; set; }
        public bool IsShow { get; set; }
        public bool IsMenuTinAnhHoatDong { get; set; }
        public string TitleMenuTinAnhHoatDong { get; set; }
        public string CategoryIdMenuTinAnhHoatDong { get; set; }
        public int OrderMenuTinAnhHoatDong { get; set; }
        public string Language { get; set; }
        public System.DateTime CreationTime { get; set; }
        public Nullable<System.Guid> CreatorId { get; set; }
        public Nullable<System.DateTime> LastModificationTime { get; set; }
        public Nullable<System.Guid> LastModifierId { get; set; }
    }
}
