//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QHBASE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> TenantId { get; set; }
        public string Title { get; set; }
        public Nullable<System.Guid> ParentID { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<int> Order { get; set; }
        public bool IsShow { get; set; }
        public bool MenuHead { get; set; }
        public bool MenuMain { get; set; }
        public bool MenuFooter { get; set; }
        public bool MenuLeft { get; set; }
        public bool MenuRight { get; set; }
        public int Type { get; set; }
        public string PageUrl { get; set; }
        public string Language { get; set; }
        public string TreeParentIds { get; set; }
        public string DetailMenuRoot { get; set; }
        public string TextClass { get; set; }
        public Nullable<bool> LinkTaget { get; set; }
        public System.DateTime CreationTime { get; set; }
        public Nullable<System.Guid> CreatorId { get; set; }
        public Nullable<System.DateTime> LastModificationTime { get; set; }
        public Nullable<System.Guid> LastModifierId { get; set; }
    }
}
