//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QHBASE
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Portal_Moet_CoCauToChucServiceEntities : DbContext
    {
        public Portal_Moet_CoCauToChucServiceEntities()
            : base("name=Portal_Moet_CoCauToChucServiceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AcademicRank> AcademicRanks { get; set; }
        public virtual DbSet<DaiBieuChuyenTrach> DaiBieuChuyenTraches { get; set; }
        public virtual DbSet<DaiBieuQuocHoi> DaiBieuQuocHois { get; set; }
        public virtual DbSet<DaiBieuQuocHoiMapDmChucDanh> DaiBieuQuocHoiMapDmChucDanhs { get; set; }
        public virtual DbSet<DaiBieuQuocHoiMapDmCoQuanQuocHoi> DaiBieuQuocHoiMapDmCoQuanQuocHois { get; set; }
        public virtual DbSet<DaiBieuQuocHoiMapDmKhoaQuocHoi> DaiBieuQuocHoiMapDmKhoaQuocHois { get; set; }
        public virtual DbSet<Degree> Degrees { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<DmChucDanh> DmChucDanhs { get; set; }
        public virtual DbSet<DmCoQuanQuocHoi> DmCoQuanQuocHois { get; set; }
        public virtual DbSet<DmDanToc> DmDanTocs { get; set; }
        public virtual DbSet<DmKhoaQuocHoi> DmKhoaQuocHois { get; set; }
        public virtual DbSet<DmLichLamViec> DmLichLamViecs { get; set; }
        public virtual DbSet<DmTonGiao> DmTonGiaos { get; set; }
        public virtual DbSet<DonViMapChucVu> DonViMapChucVus { get; set; }
        public virtual DbSet<GioiTinh> GioiTinhs { get; set; }
        public virtual DbSet<LichLamViec> LichLamViecs { get; set; }
        public virtual DbSet<Nation> Nations { get; set; }
        public virtual DbSet<NoiUngCu> NoiUngCus { get; set; }
        public virtual DbSet<OfficerMapperPossition> OfficerMapperPossitions { get; set; }
        public virtual DbSet<Officer> Officers { get; set; }
        public virtual DbSet<Position> Positions { get; set; }
        public virtual DbSet<QuocHoiHistory> QuocHoiHistories { get; set; }
        public virtual DbSet<ThongTinCanBo> ThongTinCanBoes { get; set; }
        public virtual DbSet<TimeLineDBQH> TimeLineDBQHs { get; set; }
        public virtual DbSet<TrinhDoChinhTri> TrinhDoChinhTris { get; set; }
        public virtual DbSet<TrinhDoHocVan> TrinhDoHocVans { get; set; }
    }
}
