//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QHBASE
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Portal_Moet_VanbanServiceEntities : DbContext
    {
        public Portal_Moet_VanbanServiceEntities()
            : base("name=Portal_Moet_VanbanServiceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EffectStatu> EffectStatus { get; set; }
        public virtual DbSet<Field> Fields { get; set; }
        public virtual DbSet<GopYVanBanDuThao> GopYVanBanDuThaos { get; set; }
        public virtual DbSet<Law> Laws { get; set; }
        public virtual DbSet<LawCategory> LawCategories { get; set; }
        public virtual DbSet<LawField> LawFields { get; set; }
        public virtual DbSet<LawSigner> LawSigners { get; set; }
        public virtual DbSet<Promulgator> Promulgators { get; set; }
        public virtual DbSet<Signer> Signers { get; set; }
        public virtual DbSet<TuLieuAnPham> TuLieuAnPhams { get; set; }
        public virtual DbSet<TypeOfDocument> TypeOfDocuments { get; set; }
        public virtual DbSet<VanBanDuThao> VanBanDuThaos { get; set; }
        public virtual DbSet<VBDTField> VBDTFields { get; set; }
    }
}
