//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QHBASE
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Portal_Moet_HinhanhServiceEntities : DbContext
    {
        public Portal_Moet_HinhanhServiceEntities()
            : base("name=Portal_Moet_HinhanhServiceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CategoryGallery> CategoryGallerys { get; set; }
        public virtual DbSet<CategoryVideo> CategoryVideos { get; set; }
        public virtual DbSet<Gallery> Gallerys { get; set; }
        public virtual DbSet<Video> Videos { get; set; }
    }
}
