//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QHBASE
{
    using System;
    using System.Collections.Generic;
    
    public partial class New
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public New()
        {
            this.CommentNews = new HashSet<CommentNew>();
            this.NewCategories = new HashSet<NewCategory>();
            this.NewCoQuans = new HashSet<NewCoQuan>();
            this.NewDBQHs = new HashSet<NewDBQH>();
            this.NewKyHops = new HashSet<NewKyHop>();
            this.NewPhienHops = new HashSet<NewPhienHop>();
            this.NewVersions = new HashSet<NewVersion>();
            this.ReplyNews = new HashSet<ReplyNew>();
            this.SummaryNewsses = new HashSet<SummaryNewss>();
            this.Events = new HashSet<Event>();
        }
    
        public string Id { get; set; }
        public Nullable<System.Guid> TenantId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Content { get; set; }
        public Nullable<int> Status { get; set; }
        public string Image { get; set; }
        public string Author { get; set; }
        public string Source { get; set; }
        public Nullable<int> ReadCount { get; set; }
        public Nullable<bool> ShowDescription { get; set; }
        public Nullable<bool> AllowComment { get; set; }
        public Nullable<bool> Shared { get; set; }
        public Nullable<bool> Hot { get; set; }
        public Nullable<System.DateTime> DatePublic { get; set; }
        public string PageTitleSEO { get; set; }
        public string PageUrlSEO { get; set; }
        public string DescriptionSEO { get; set; }
        public string KeyMainSEO { get; set; }
        public string KeyWordsSEO { get; set; }
        public Nullable<System.DateTime> ApprovedByPublicSendToTime { get; set; }
        public Nullable<System.Guid> ApprovedByPublicId { get; set; }
        public Nullable<System.DateTime> ApprovedByPublicTime { get; set; }
        public string ApprovedByPublicName { get; set; }
        public string DeletionName { get; set; }
        public string CreatorName { get; set; }
        public string LastModifierName { get; set; }
        public string Language { get; set; }
        public Nullable<bool> IsPublished { get; set; }
        public string OldId { get; set; }
        public Nullable<bool> StatusEndLive { get; set; }
        public string UrlEMagazine { get; set; }
        public Nullable<int> TypeNewContent { get; set; }
        public Nullable<System.Guid> TypeNewId { get; set; }
        public string ExtraProperties { get; set; }
        public string ConcurrencyStamp { get; set; }
        public System.DateTime CreationTime { get; set; }
        public Nullable<System.Guid> CreatorId { get; set; }
        public Nullable<System.DateTime> LastModificationTime { get; set; }
        public Nullable<System.Guid> LastModifierId { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.Guid> DeleterId { get; set; }
        public Nullable<System.DateTime> DeletionTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommentNew> CommentNews { get; set; }
        public virtual TypeNew TypeNew { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NewCategory> NewCategories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NewCoQuan> NewCoQuans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NewDBQH> NewDBQHs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NewKyHop> NewKyHops { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NewPhienHop> NewPhienHops { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NewVersion> NewVersions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReplyNew> ReplyNews { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SummaryNewss> SummaryNewsses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Event> Events { get; set; }
    }
}
