//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QHBASE
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewsCat
    {
        public int CatID { get; set; }
        public string CatName { get; set; }
        public string CatUrl { get; set; }
        public Nullable<int> CatParentId { get; set; }
        public Nullable<int> CatOldID { get; set; }
        public string CategoryAllID { get; set; }
        public Nullable<int> IsShow { get; set; }
        public Nullable<int> IsDBQH { get; set; }
        public Nullable<int> IsTopMenu { get; set; }
        public string Description { get; set; }
        public string TitleSort { get; set; }
        public string IndexCat { get; set; }
    }
}
