//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QHBASE
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public News()
        {
            this.NewsEvents = new HashSet<NewsEvent>();
        }
    
        public int ID { get; set; }
        public string Category { get; set; }
        public string Title { get; set; }
        public string IdLoaiTin { get; set; }
        public string Event { get; set; }
        public string Image { get; set; }
        public Nullable<int> AllowComment { get; set; }
        public Nullable<int> ShowImage { get; set; }
        public string Description { get; set; }
        public string ContentNew { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> ShowDescription { get; set; }
        public string ReadCount { get; set; }
        public string AuthorNews { get; set; }
        public string SourceNews { get; set; }
        public string Created { get; set; }
        public string Author { get; set; }
        public string NoiDungChinhSua { get; set; }
        public Nullable<int> TrangThaiTin { get; set; }
        public Nullable<int> Hotnews { get; set; }
        public Nullable<int> IsLive { get; set; }
        public Nullable<int> IsShare { get; set; }
        public Nullable<int> IsShowView { get; set; }
        public string Keywords { get; set; }
        public Nullable<int> ModerationStatus { get; set; }
        public Nullable<int> OldID { get; set; }
        public Nullable<int> Attachment { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NewsEvent> NewsEvents { get; set; }
    }
}
