//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QHBASE
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewTypeNew
    {
        public string NewId { get; set; }
        public System.Guid TypeNewId { get; set; }
        public string OldId { get; set; }
        public Nullable<int> TypeNewContent { get; set; }
        public System.Guid Id { get; set; }
    }
}
