//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QHBASE
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewVersion
    {
        public string Id { get; set; }
        public Nullable<System.Guid> TenantId { get; set; }
        public string NewId { get; set; }
        public string Content { get; set; }
        public string CreatorIdBy { get; set; }
        public bool IsCreate { get; set; }
        public System.DateTime CreationTime { get; set; }
        public Nullable<System.Guid> CreatorId { get; set; }
        public string VersionNo { get; set; }
        public string Language { get; set; }
    
        public virtual New New { get; set; }
    }
}
