//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QHBASE
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhuanBut
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> TenantId { get; set; }
        public string TieuDeBaiViet { get; set; }
        public string IdBaiViet { get; set; }
        public string TheLoaiTinName { get; set; }
        public string NguoiNhuanButName { get; set; }
        public Nullable<System.Guid> NguoiNhuanButId { get; set; }
        public Nullable<decimal> MucLuongCoSo { get; set; }
        public Nullable<decimal> HeSoLuongCoBan { get; set; }
        public Nullable<decimal> NgayCongLamViec { get; set; }
        public string TheLoaiTinId { get; set; }
        public Nullable<decimal> DoDaiTinThucTe { get; set; }
        public Nullable<decimal> SoLuongDoDaiTin { get; set; }
        public Nullable<decimal> HeSoNhuanBut { get; set; }
        public Nullable<decimal> NhuanButDuocHuong { get; set; }
        public Nullable<decimal> DinhMucKhoanNhuanBut { get; set; }
        public Nullable<int> Month { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> LoaiNhuanBut { get; set; }
        public Nullable<bool> IsShow { get; set; }
        public Nullable<int> Order { get; set; }
        public string CreatorName { get; set; }
        public string LastModifierName { get; set; }
        public string DeletedName { get; set; }
        public Nullable<System.Guid> ParentId { get; set; }
        public Nullable<decimal> TongNhuanBut { get; set; }
        public Nullable<bool> IsHeSoLuongConfig { get; set; }
        public System.DateTime CreationTime { get; set; }
        public Nullable<System.Guid> CreatorId { get; set; }
        public Nullable<System.DateTime> LastModificationTime { get; set; }
        public Nullable<System.Guid> LastModifierId { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.Guid> DeleterId { get; set; }
        public Nullable<System.DateTime> DeletionTime { get; set; }
    }
}
