//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QHBASE
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhuanButConfig
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> TenantId { get; set; }
        public string Title { get; set; }
        public string TheLoaiTinName { get; set; }
        public Nullable<decimal> DonViDoDaiTin { get; set; }
        public Nullable<decimal> HeSoGiaTriTinBai { get; set; }
        public Nullable<decimal> HeSoNhuanButToiDa { get; set; }
        public Nullable<decimal> GiaTriDonViHeSoNhuanBut { get; set; }
        public Nullable<int> LoaiNhuanBut { get; set; }
        public Nullable<bool> IsShow { get; set; }
        public Nullable<int> Order { get; set; }
        public string CreatorName { get; set; }
        public string LastModifierName { get; set; }
        public string DeletedName { get; set; }
        public System.DateTime CreationTime { get; set; }
        public Nullable<System.Guid> CreatorId { get; set; }
        public Nullable<System.DateTime> LastModificationTime { get; set; }
        public Nullable<System.Guid> LastModifierId { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.Guid> DeleterId { get; set; }
        public Nullable<System.DateTime> DeletionTime { get; set; }
    }
}
