//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QHBASE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> TenantId { get; set; }
        public string Title { get; set; }
        public Nullable<int> NAction { get; set; }
        public int NType { get; set; }
        public string EntityId { get; set; }
        public string Content { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.Guid> OwnerId { get; set; }
        public string OwnerUserName { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public string Address { get; set; }
        public string Language { get; set; }
        public bool IsRead { get; set; }
        public Nullable<bool> Hidden { get; set; }
        public string ReadByUserIds { get; set; }
        public Nullable<System.DateTime> OwnerCreateTime { get; set; }
        public string PhienOrKyId { get; set; }
        public Nullable<int> PhienOrKy { get; set; }
        public Nullable<int> TypeOfND { get; set; }
        public string PhienOrKyName { get; set; }
        public string KhoaQuocHoiName { get; set; }
        public string KhoaQuocHoiID { get; set; }
        public System.DateTime CreationTime { get; set; }
        public Nullable<System.Guid> CreatorId { get; set; }
        public Nullable<System.DateTime> LastModificationTime { get; set; }
        public Nullable<System.Guid> LastModifierId { get; set; }
    }
}
