//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QHBASE
{
    using System;
    using System.Collections.Generic;
    
    public partial class OfficerMapperPossition
    {
        public System.Guid OfficerId { get; set; }
        public System.Guid PositionId { get; set; }
        public System.Guid DepartmentId { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual Officer Officer { get; set; }
        public virtual Position Position { get; set; }
    }
}
