//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QHBASE
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuangCaoss
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QuangCaoss()
        {
            this.ViTriQuangCaoMapQuangCaos = new HashSet<ViTriQuangCaoMapQuangCao>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> TenantId { get; set; }
        public string Title { get; set; }
        public string Image { get; set; }
        public string LinkUrl { get; set; }
        public Nullable<int> Order { get; set; }
        public bool Visibility { get; set; }
        public Nullable<System.DateTime> PublishDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public string DeletedBy { get; set; }
        public string OrganizationUnitCode { get; set; }
        public Nullable<System.Guid> OrganizationUnitId { get; set; }
        public string OrganizationUnitName { get; set; }
        public string Language { get; set; }
        public string Position { get; set; }
        public Nullable<bool> IsTargetBlank { get; set; }
        public string ListChuyenTinText { get; set; }
        public System.DateTime CreationTime { get; set; }
        public Nullable<System.Guid> CreatorId { get; set; }
        public Nullable<System.DateTime> LastModificationTime { get; set; }
        public Nullable<System.Guid> LastModifierId { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.Guid> DeleterId { get; set; }
        public Nullable<System.DateTime> DeletionTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ViTriQuangCaoMapQuangCao> ViTriQuangCaoMapQuangCaos { get; set; }
    }
}
