//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QHBASE
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReadCountLog
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> TenantId { get; set; }
        public Nullable<System.DateTime> ViewTime { get; set; }
        public Nullable<int> TypeCategoryLog { get; set; }
        public Nullable<int> TypeSubCategoryLog { get; set; }
        public string IpAddress { get; set; }
        public string SubCategoryID { get; set; }
        public string SubCategoryTitle { get; set; }
        public string EntityId { get; set; }
        public string EntityTitle { get; set; }
        public Nullable<System.Guid> CreatorEntityId { get; set; }
        public string Language { get; set; }
        public System.DateTime CreationTime { get; set; }
        public Nullable<System.Guid> CreatorId { get; set; }
        public Nullable<System.DateTime> LastModificationTime { get; set; }
        public Nullable<System.Guid> LastModifierId { get; set; }
    }
}
