//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QHBASE
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReplyNoiDung
    {
        public System.Guid Id { get; set; }
        public string ReplyByContent { get; set; }
        public Nullable<System.Guid> ReplyByUserId { get; set; }
        public string ReplyByUserName { get; set; }
        public Nullable<System.DateTime> ReplyByUserTime { get; set; }
        public System.Guid NoiDungId { get; set; }
    }
}
