//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QHBASE
{
    using System;
    using System.Collections.Generic;
    
    public partial class SettingSiteClone
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> TenantId { get; set; }
        public string Title { get; set; }
        public Nullable<bool> Show { get; set; }
        public string LinkWeb { get; set; }
        public string PathCloneContent { get; set; }
        public string CreatorName { get; set; }
        public string LastModifierName { get; set; }
        public System.DateTime CreationTime { get; set; }
        public Nullable<System.Guid> CreatorId { get; set; }
        public Nullable<System.DateTime> LastModificationTime { get; set; }
        public Nullable<System.Guid> LastModifierId { get; set; }
    }
}
