//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QHBASE
{
    using System;
    using System.Collections.Generic;
    
    public partial class SummaryNewss
    {
        public string Id { get; set; }
        public Nullable<System.Guid> TenantId { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public int Status { get; set; }
        public Nullable<System.DateTime> CreationTime { get; set; }
        public Nullable<System.Guid> CreationId { get; set; }
        public string CreationName { get; set; }
        public string NewId { get; set; }
        public Nullable<bool> IsShared { get; set; }
        public string Language { get; set; }
    
        public virtual New New { get; set; }
    }
}
