//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QHBASE
{
    using System;
    using System.Collections.Generic;
    
    public partial class TagInfo
    {
        public System.Guid Id { get; set; }
        public string Title { get; set; }
        public string Language { get; set; }
        public string CreatedBy { get; set; }
        public string TagId { get; set; }
        public string EntityId { get; set; }
        public string Descriptions { get; set; }
        public string CategoryId { get; set; }
        public string Image { get; set; }
        public Nullable<System.DateTime> DatePublic { get; set; }
        public int TagEntityType { get; set; }
        public string Status { get; set; }
        public string TypeOfND { get; set; }
        public Nullable<System.DateTime> CreationTimeEntity { get; set; }
        public Nullable<System.Guid> TenantId { get; set; }
        public string ExtraProperties { get; set; }
        public string ConcurrencyStamp { get; set; }
        public System.DateTime CreationTime { get; set; }
        public Nullable<System.Guid> CreatorId { get; set; }
    
        public virtual Tag Tag { get; set; }
    }
}
