//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QHBASE
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongTinCanBo
    {
        public string Id { get; set; }
        public Nullable<System.Guid> TenantId { get; set; }
        public string FullName { get; set; }
        public string SurName { get; set; }
        public string Name { get; set; }
        public string Image { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string NgheNghiepChucVu { get; set; }
        public string NoiLamViec { get; set; }
        public string DienThoaiCoQuan { get; set; }
        public string DienThoaiNhaRieng { get; set; }
        public string DienThoaiDiDong { get; set; }
        public string Email { get; set; }
        public string NoiDung { get; set; }
        public string Fax { get; set; }
        public bool IsShow { get; set; }
        public string UpdatedBy { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.Guid> GioiTinhId { get; set; }
        public Nullable<System.Guid> CoQuanQuocHoiId { get; set; }
        public Nullable<System.Guid> ChucVuId { get; set; }
        public int Order { get; set; }
        public string Language { get; set; }
        public string ExtraProperties { get; set; }
        public string ConcurrencyStamp { get; set; }
        public System.DateTime CreationTime { get; set; }
        public Nullable<System.Guid> CreatorId { get; set; }
        public Nullable<System.DateTime> LastModificationTime { get; set; }
        public Nullable<System.Guid> LastModifierId { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.Guid> DeleterId { get; set; }
        public Nullable<System.DateTime> DeletionTime { get; set; }
    
        public virtual DmChucDanh DmChucDanh { get; set; }
        public virtual DmCoQuanQuocHoi DmCoQuanQuocHoi { get; set; }
        public virtual GioiTinh GioiTinh { get; set; }
    }
}
