//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QHBASE
{
    using System;
    using System.Collections.Generic;
    
    public partial class TuLieuAnPham
    {
        public string Id { get; set; }
        public Nullable<System.Guid> TenantId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Content { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public string DeletedBy { get; set; }
        public string Author { get; set; }
        public string Source { get; set; }
        public string Image { get; set; }
        public Nullable<System.DateTime> PublicDate { get; set; }
        public string LoaiTuLieuAnPhamId { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> SoTrang { get; set; }
        public Nullable<int> ReadCount { get; set; }
        public string PageTitleSEO { get; set; }
        public string PageUrlSEO { get; set; }
        public string DescriptionSEO { get; set; }
        public string KeyMainSEO { get; set; }
        public string KeyWordsSEO { get; set; }
        public Nullable<bool> Shared { get; set; }
        public string Language { get; set; }
        public string ExtraProperties { get; set; }
        public string ConcurrencyStamp { get; set; }
        public System.DateTime CreationTime { get; set; }
        public Nullable<System.Guid> CreatorId { get; set; }
        public Nullable<System.DateTime> LastModificationTime { get; set; }
        public Nullable<System.Guid> LastModifierId { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.Guid> DeleterId { get; set; }
        public Nullable<System.DateTime> DeletionTime { get; set; }
    }
}
