//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QHBASE
{
    using System;
    using System.Collections.Generic;
    
    public partial class VanKienMapCQBH
    {
        public System.Guid VanKienTaiLieuId { get; set; }
        public System.Guid CQBHId { get; set; }
        public Nullable<int> OldVanKienId { get; set; }
    
        public virtual VanKienTaiLieu VanKienTaiLieu { get; set; }
    }
}
