//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QHBASE
{
    using System;
    using System.Collections.Generic;
    
    public partial class VanKien
    {
        public int VanKienID { get; set; }
        public string Title { get; set; }
        public string DMCoQuan { get; set; }
        public string NoiDungHTML { get; set; }
        public string DMLinhVuc { get; set; }
        public Nullable<int> VanKienOldId { get; set; }
        public string DMVanKien { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<int> Attachments { get; set; }
        public Nullable<int> ModerationStatus { get; set; }
    }
}
