//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QHBASE
{
    using System;
    using System.Collections.Generic;
    
    public partial class VietLaw
    {
        public int ID { get; set; }
        public string SoHieu { get; set; }
        public string TrichYeu { get; set; }
        public Nullable<System.DateTime> NgayBanHanh { get; set; }
        public string CoQuanBanHanh { get; set; }
        public string NguoiKy { get; set; }
        public Nullable<System.DateTime> NgayHieuLuc { get; set; }
        public string LoaiVanBan { get; set; }
        public string ToanVan { get; set; }
        public byte[] FileData { get; set; }
        public Nullable<System.DateTime> NgayHetHieuLuc { get; set; }
        public int VanBanLienQuan { get; set; }
        public Nullable<int> OldID { get; set; }
        public string TuKhoa { get; set; }
        public Nullable<int> OldID_Index { get; set; }
    }
}
