//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QHBASE
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViTriQuangCaoMapQuangCao
    {
        public System.Guid QuangCaoId { get; set; }
        public System.Guid ViTriQuangCaoId { get; set; }
        public Nullable<System.Guid> TenantId { get; set; }
    
        public virtual QuangCaoss QuangCaoss { get; set; }
        public virtual ViTriQuangCao ViTriQuangCao { get; set; }
    }
}
