//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QHBASE
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkflowInstance
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WorkflowInstance()
        {
            this.HistoryActionFlows = new HashSet<HistoryActionFlow>();
        }
    
        public System.Guid Id { get; set; }
        public string TARGET_OBJECT_ID { get; set; }
        public string TARGET_OBJECT_TABLE { get; set; }
        public System.Guid WORKFLOW_DEFINITION_ID { get; set; }
        public string LIST_RELATED_OBJECT { get; set; }
        public string WORKFLOW_DATA { get; set; }
        public string LIST_AVAILABLE_NODE_ID { get; set; }
        public string LIST_VIEWER_ID { get; set; }
        public string LIST_HANDLER_ID { get; set; }
        public string TARGET_OBJECT_NAME { get; set; }
        public string LIST_RELATED_OBJECT_NAME { get; set; }
        public Nullable<System.DateTime> FINISH_TIME { get; set; }
        public int WORKFLOW_INSTANCE_STATUS { get; set; }
        public Nullable<System.Guid> WORKFLOW_INSTANCE_PARENT_ID { get; set; }
        public string WORKFLOW_INSTANCE_PARENT_NODE_ID { get; set; }
        public string TARGET_OBJECT_HANDLER { get; set; }
        public string LIST_RELATED_OBJECT_ORIGINAL { get; set; }
        public string TARGET_OBJECT_PARENT_ID { get; set; }
        public string TARGET_OBJECT_PARENT_TABLE { get; set; }
        public string CreatedBy { get; set; }
        public string ExtraProperties { get; set; }
        public string ConcurrencyStamp { get; set; }
        public System.DateTime CreationTime { get; set; }
        public Nullable<System.Guid> CreatorId { get; set; }
        public Nullable<System.DateTime> LastModificationTime { get; set; }
        public Nullable<System.Guid> LastModifierId { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.Guid> DeleterId { get; set; }
        public Nullable<System.DateTime> DeletionTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistoryActionFlow> HistoryActionFlows { get; set; }
        public virtual WorkflowDefinition WorkflowDefinition { get; set; }
    }
}
