//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QHBASE
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkflowDefinition
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WorkflowDefinition()
        {
            this.WorkflowInstances = new HashSet<WorkflowInstance>();
        }
    
        public System.Guid Id { get; set; }
        public string WORKFLOW_NAME { get; set; }
        public string WORKFLOW_DATA { get; set; }
        public string LIST_UPGRADE_USER_ID { get; set; }
        public string LIST_UPGRADE_USER_NAME { get; set; }
        public string LIST_UPGRADE_TIME { get; set; }
        public string CREATE_BY { get; set; }
        public string UPDATE_BY { get; set; }
        public Nullable<int> STATUS { get; set; }
        public string DESCRIPTION { get; set; }
        public string TYPE_WORKFLOW { get; set; }
        public string LST_WORKFLOW_CHILD { get; set; }
        public bool STATIC_STATUS { get; set; }
        public Nullable<int> LoaiQuyTrinhId { get; set; }
        public string ExtraProperties { get; set; }
        public string ConcurrencyStamp { get; set; }
        public System.DateTime CreationTime { get; set; }
        public Nullable<System.Guid> CreatorId { get; set; }
        public Nullable<System.DateTime> LastModificationTime { get; set; }
        public Nullable<System.Guid> LastModifierId { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.Guid> DeleterId { get; set; }
        public Nullable<System.DateTime> DeletionTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkflowInstance> WorkflowInstances { get; set; }
    }
}
